name: Deployment

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    name: Deploy lambda function
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Go
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      
      - name: Build & Zip
        run: |
          GOOS=linux GOARCH=amd64 go build -o main ./cmd/server/main.go
          zip -r main.zip main

      - name: AWS Lambda Deploy
        uses: appleboy/lambda-action@master
        env:
          ENVIRONMENT: dev
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: lambda-checkout-facilittei-${{ env.ENVIRONMENT }}
          zip_file: main.zip
          dry_run: true
          environment: VERSION=${{ github.sha }}
