name: Deployment

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    name: Deploy lambda function
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16.3'
      - run: GOOS=linux GOARCH=amd64 go build -ldflags="-X 'github.com/facilittei/checkout-listener/handlers.Version=${{ github.sha }}'" -o main ./cmd/server/main.go

      - name: Zip
        run: zip -r main.zip main

      - name: AWS Lambda Deploy
        uses: appleboy/lambda-action@master
        env:
          ENVIRONMENT: dev
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: lambda-checkout-facilittei-${{ env.ENVIRONMENT }}
          zip_file: main.zip
          environment: PAYMENT_GATEWAY_URL=${{ secrets.PAYMENT_GATEWAY_URL }},REDIS_HOST=${{ secrets.REDIS_HOST }},REDIS_PORT=${{ secrets.REDIS_PORT }}
