name: Deployment

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    name: Deploy lambda function
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: AWS Lambda Deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: checkout-listener
          zip_file: output.zip
          dry_run: true
          environment: VERSION=${{ github.sha }}
